// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-rooms.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.2";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-rooms.ts
var list_rooms_default = defineTool({
  name: "list_rooms",
  title: "List rooms",
  description: "List the published Malar Park guest rooms with their name, slug, description and nightly price in INR.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of rooms to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("rooms").select("name, slug, description, price, sort").eq("enabled", true).order("sort").limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const rooms = (data ?? []).map((r) => ({
      name: r.name,
      slug: r.slug,
      description: r.description ?? "",
      pricePerNightInr: r.price ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rooms, null, 2) }],
      structuredContent: { rooms }
    };
  }
});

// src/lib/mcp/tools/list-faqs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_faqs_default = defineTool2({
  name: "list_faqs",
  title: "List FAQs",
  description: "List the published Malar Park frequently asked questions and their answers. Optionally filter by a keyword.",
  inputSchema: {
    search: z2.string().optional().describe("Optional keyword to match against the question text."),
    limit: z2.number().int().min(1).max(100).optional().describe("Maximum number of FAQs to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("faqs").select("question, answer_html, sort").eq("enabled", true).order("sort").limit(limit ?? 50);
    if (search?.trim()) query = query.ilike("question", `%${search.trim()}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const faqs = (data ?? []).map((f) => ({
      question: f.question,
      answer: (f.answer_html ?? "").replace(/<[^>]*>/g, "").trim()
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(faqs, null, 2) }],
      structuredContent: { faqs }
    };
  }
});

// src/lib/mcp/tools/list-reviews.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var list_reviews_default = defineTool3({
  name: "list_reviews",
  title: "List guest reviews",
  description: "List published guest reviews for Malar Park, featured/pinned reviews first, with rating and guest name.",
  inputSchema: {
    minRating: z3.number().int().min(1).max(5).optional().describe("Only return reviews with at least this star rating."),
    limit: z3.number().int().min(1).max(50).optional().describe("Maximum number of reviews to return. Defaults to 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ minRating, limit }) => {
    const supabase = supabaseAnon();
    let query = supabase.from("reviews").select("guest_name, rating, text, country, featured, sort").eq("enabled", true).order("featured", { ascending: false }).order("sort").limit(limit ?? 20);
    if (minRating) query = query.gte("rating", minRating);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const reviews = (data ?? []).map((r) => ({
      guestName: r.guest_name,
      rating: r.rating,
      review: r.text,
      country: r.country ?? null,
      pinned: r.featured
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(reviews, null, 2) }],
      structuredContent: { reviews }
    };
  }
});

// src/lib/mcp/tools/list-amenities.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var list_amenities_default = defineTool4({
  name: "list_amenities",
  title: "List hotel amenities",
  description: "List the published amenities and facilities offered at Malar Park hotel.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Maximum number of amenities to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("amenities").select("title, description, sort").eq("enabled", true).order("sort").limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const amenities = (data ?? []).map((a) => ({
      title: a.title,
      description: a.description ?? ""
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(amenities, null, 2) }],
      structuredContent: { amenities }
    };
  }
});

// src/lib/mcp/tools/list-attractions.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^4.4.3";
var list_attractions_default = defineTool5({
  name: "list_attractions",
  title: "List nearby attractions",
  description: "List nearby attractions and places of interest around Malar Park in Tiruvannamalai, with distance where available.",
  inputSchema: {
    limit: z5.number().int().min(1).max(100).optional().describe("Maximum number of attractions to return. Defaults to 50.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = supabaseAnon();
    const { data, error } = await supabase.from("attractions").select("title, description, distance, sort").eq("enabled", true).order("sort").limit(limit ?? 50);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const attractions = (data ?? []).map((a) => ({
      title: a.title,
      description: a.description ?? "",
      distance: a.distance ?? null
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(attractions, null, 2) }],
      structuredContent: { attractions }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "malar-park-digital",
  title: "Malar Park Digital",
  version: "0.1.0",
  instructions: "Tools for Malar Park hotel in Tiruvannamalai. Use `list_rooms` for room types and nightly INR rates, `list_amenities` for facilities, `list_faqs` for guest questions, `list_reviews` for guest feedback, and `list_attractions` for nearby places. All data is public website content.",
  tools: [
    list_rooms_default,
    list_amenities_default,
    list_faqs_default,
    list_reviews_default,
    list_attractions_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
